<a href="https://colab.research.google.com/github/dwipaprasetyo/PSDS_Kelas_Dasar_3.0/blob/main/M4P1V1_Operasi_Numpy_dan_Matriks_dwipa_prasetyo_priyoko.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array

Numpy merupakan salah satu library Python yang banyak digunakan dalam proses analisis data karena fiturnya yang hebat

In [1]:
import numpy as np

## Membuat Array Numpy

Kita bisa membuat Array menggunakan NumPy dengan membungkusnya terlebih dahulu di List dan dirubah menjadi numpy array.

In [2]:
list_1 = [1,2,3,4,5]
arr_1 = np.array([list_1])
arr_1

array([[1, 2, 3, 4, 5]])

Beberapa fungsi yang dapat digunakan dalam membuat array 

```
zeros()    -> Membuat array dengan nilai 0
ones()     -> Membuat array dengan nilai 1
arange()   -> Membuat array dengan nilai dalam range 
linspace() -> Membuat array dengan nilai dalam interval
logspace() -> Membuat array dengan nilai log Base10 dalam interval
full       -> Membuat array dengan semua elemen penyusunnya sama
full_like  -> Membuat array dengan semua elemen penyusunnya sama namun ukurannya dari array lainnya
identity   -> Membuat array matriks identitas
repeat     -> Membuat array dengan perulangan array atau sequence 
```

In [3]:
print(np.zeros((2,5))) # membuat array dengan nilai 0 dengan shape (2,5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
print(np.ones((5,3))) # membuat array dengan nilai 1 dengan shape (5,3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
print(np.arange(1, 10, 2)) #arange(start, stop, step)

[1 3 5 7 9]


In [6]:
print(np.linspace(1, 10, 2)) # linespace(start, stop, number)

[ 1. 10.]


In [7]:
print(np.logspace(1, 10, 2)) # logspace(start, stop, number)

[1.e+01 1.e+10]


In [8]:
print(np.full((2,2), 4)) # Membuat array matriks dengan shape (2,2) dengan elemen 4

[[4 4]
 [4 4]]


In [9]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A, 3)) # Membuat array matriks dengan shape yang sama dengan A dengan semua elemennya 3

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [10]:
print(np.random.rand(4,2)) # Random decimal numbers

[[0.29613557 0.27153517]
 [0.01352437 0.01161671]
 [0.01972725 0.48672197]
 [0.26310136 0.01329645]]


In [11]:
print(np.random.randint(-4,8, size=(3,3))) # Random Integer values

[[-3  6  7]
 [ 7  1  3]
 [ 6 -3  4]]


In [12]:
print(np.identity(5)) # Membuat matriks identitas

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
arr = np.array([[1,2,3]]) # Membuat matriks dengan perulangan array
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Metode-Metode Pada Array

Objek array pada Python Numpy memiliki berbagai method untuk melakukan operasi atau perintah-perintah tertentu. Berikut adalah fungsi-fungsi yang merupakan metode pada array yang sering dipakai:

**array.ndim**

Metode ini digunakan untuk mengetahui dimensi dari array.

In [14]:
a=np.array([29, 28, 30], dtype='int32')
print(a)

print("Dimensi dari array a adalah ", a.ndim)

[29 28 30]
Dimensi dari array a adalah  1


**array.shape**

Metode ini digunakan untuk mengetahui ukuran (variabel dan baris) dari array.

In [15]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

print("Ukuran Shape dari array b adalah ", b.shape)

[[9. 8. 7.]
 [6. 5. 4.]]
Ukuran Shape dari array b adalah  (2, 3)


**array.dtype**

Metode ini digunakan untuk mengetahui type data dari elemen penyusun array.

In [16]:
a.dtype

dtype('int32')

**array.size**

Metode ini digunakan untuk menghitung jumlah elemen dari array.

In [17]:
a.size

3

## Multidimensional Array

Salah satu fitur menarik dari NumPy adalah dia mampu membuat multidimensional array dan melakukan manipulasi array dengan mudah dan cepat

Multidimensional array adalah array yang berbentuk lebih dari 1 dimensi (1D), bisa 2D, 3D, 4D dan seterusnya

Cara membuat multidimensional array sama dengan membuat array 1 dimensi, perbedaannya hanya pada parameter yang digunakan

Berikut contohnya membuat array 2 dimensi:

In [18]:
arr_2 = np.array([[1,2,3,4,5], [2,4,6,8,10]])
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

Array diatas adalah berbentuk (2,5) artinya mempunyai 2 baris dan 5 kolom

Kita bisa melihat jumlah elemen di setiap dimensi dengan menggunakan shape

In [19]:
arr_2.shape

(2, 5)

## Indexing dan Slicing

Kita juga dapat melakukan indexing dan slicing terhadap array dengan mudah

Indexing dimulai dari 0 dan dimulai dengan notasi bracket “[ ]”

Misal kita ingin mencari nilai yang berada di index 0, 2, dan 4

In [20]:
arr_3 = np.array([1,2,3,4,5])
print(arr_3[0])
print(arr_3[2])
print(arr_3[4])

1
3
5


Untuk mengambil nilai berderet tambahkan “:”

In [21]:
arr_3 = np.array([1,2,3,4,5])
print(arr_3[0:4])

[1 2 3 4]


In [22]:
arr_4 = np.array([[1,2,3,4,5], [2,4,6,8,10]])
print(arr_4)
print(arr_4[1,3])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
8


Nilai pada kolom index ke-1 dan baris index ke-1 adalah 4

## Operasi Aritmatika

Kita bisa menggunakan operasi aritmatika seperti penjumlahan, pengurangan, perkalian, pembagian dan perpangkatan

Operator yang digunakan adalah  +, -, *, / dan **

Berikut contoh operasi aritmatika pada array

In [23]:
arr_A = np.array([1,2,3,4,5])
arr_B = np.array([2,2,2,2,2])

print("Penjumlahan = ", arr_A + arr_B)
print("Pengurangan = ", arr_A - arr_B)
print("Perkalian = ", arr_A * arr_B)
print("Pembagian = ", arr_A / arr_B)
print("Perpangkatan = ", arr_A ** arr_B)

Penjumlahan =  [3 4 5 6 7]
Pengurangan =  [-1  0  1  2  3]
Perkalian =  [ 2  4  6  8 10]
Pembagian =  [0.5 1.  1.5 2.  2.5]
Perpangkatan =  [ 1  4  9 16 25]


## Operasi Matematika

NumPy mempunyai fungsi matematika yang dapat digunakan pada Array

Beberapa contoh fungsi statistik antara lain min(), max(), mean(), sum(), std()

In [24]:
arr_5 = np.array([1,2,3,4,5])
print("Nilai minimal = ", arr_5.min())
print("Nilai maksimal = ", arr_5.max())
print("Nilai rata-rata = ", arr_5.mean())
print("Total nilai = ", arr_5.sum())
print("Standar Deviasi = ", arr_5.std())

Nilai minimal =  1
Nilai maksimal =  5
Nilai rata-rata =  3.0
Total nilai =  15
Standar Deviasi =  1.4142135623730951


Ada juga fungsi argmin() dan argmax() untuk mendapatkan index dari nilai minimum dan maksimum

In [25]:
print("Index nilai niminal = ", arr_5.argmin())
print("Index nilai maksimal = ", arr_5.argmax())

Index nilai niminal =  0
Index nilai maksimal =  4


## Transformasi Array

Kita dapat membuat array baru dari array yang sudah ada melalui berbagai metode transformasi seperti merubah ukuran, menggabungkan dua array atau lebih dan lain sebagainya.

**array.reshape**

Metode ini digunakan untuk merubah shape array dengan jumlah elemen yang tidak berubah.

In [26]:
sebelum = np.array([[1,2,3,4],[5,6,7,8]])
print(sebelum)

print("-"*20)
sesudah = sebelum.reshape((4,2))
print(sesudah)

[[1 2 3 4]
 [5 6 7 8]]
--------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Perhatikan bahwa array `sebelum` memiliki jumlah elemen 8 (2,4) dan array `sesudah` juga memiliki jumlah elemen 8 (4,2).

**array.vstack**

Metode ini dilakukan untuk menumpuk beberapa array secara vertikal

In [27]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

**array.hstack**

Metode ini dilakukan untuk menumpuk beberapa array secara horizontal.

In [28]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2)

print(np.hstack((h1,h2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


# **Representasi Matriks Pada Python**

Matriks adalah array 2 dimensi khusus yang mempertahankan sifat 2 dimensinnya melalui operasi. Matriks memiliki operator khusus tertentu, seperti perkalian matriks dan pemangkatan matriks.

Berikut adalah beberapa penulisan python di berbagai platform:

![alt text](https://drive.google.com/uc?id=1Vo7_qxBo3AGaKDtS1nym0Q-hq1Rxh2JH
)



Berikut contoh penulisan matriks pada python:

In [29]:
import numpy as np

In [30]:
A = np.array([[1, 2], [4, 5]])
A

array([[1, 2],
       [4, 5]])

In [31]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **Operasi Matriks Pada Python**

In [32]:
P = np.array([[1, 2], [4, 5]])
P

array([[1, 2],
       [4, 5]])

In [33]:
Q = np.array([[7, 8], [9, 10]])
Q

array([[ 7,  8],
       [ 9, 10]])

In [34]:
a=29
a

29

**Penjumlahan Matriks**

In [35]:
np.add(P,Q)

array([[ 8, 10],
       [13, 15]])

**Pengurangan Matriks**

In [36]:
np.subtract(P,Q)

array([[-6, -6],
       [-5, -5]])

**Perkalian Skalar Matriks**

In [37]:
a*P

array([[ 29,  58],
       [116, 145]])

**Perkalian Matriks**

In [38]:
np.multiply(P,Q)

array([[ 7, 16],
       [36, 50]])

**Perkalian Titik Matriks (Dot Product)**

In [39]:
np.dot(P,Q)

array([[25, 28],
       [73, 82]])

**Transpose Matriks**

In [40]:
P.T

array([[1, 4],
       [2, 5]])

**Operasi Fungsi Pada Setiap Elemen Matriks - Akar Kuadrat**

In [41]:
np.sqrt(P)

array([[1.        , 1.41421356],
       [2.        , 2.23606798]])

**Menjumlahkan Semua Elemen Kolom Sebuah Matriks**

In [42]:
Q

array([[ 7,  8],
       [ 9, 10]])

In [43]:
np.sum(Q,axis=1)

array([15, 19])

**Menjumlahkan semua elemen baris sebuah matriks**

In [44]:
np.sum(Q,axis=0)

array([16, 18])

# **Aljabar Linear Pada Python**

Dalam modul numpy juga disediakan fungsi-fungsi Aljabar Linear untuk matriks.
Beberapa konsep Aljabar Linear yang akan ditunjukkan di modul ini adalah
* Determinan
* Inverse
* Nilai eigen
* Vector eigen
* Matriks identitas
* Matriks satuan
* Matriks nol
* Matriks segitiga L dan U
* Dekomposisi L U matriks

In [45]:
A = np.array([[2,3,4],[7, 8, 9],[10, 7, 8]])
A

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [10,  7,  8]])

In [46]:
B = np.array([[5,7,4],[6, 8, 9],[1, 2, 6]])
B

array([[5, 7, 4],
       [6, 8, 9],
       [1, 2, 6]])

**Determinan**


In [47]:
np.linalg.det(A)

-20.000000000000007

**Inverse Matriks**

In [48]:
np.linalg.inv(A)

array([[-0.05, -0.2 ,  0.25],
       [-1.7 ,  1.2 , -0.5 ],
       [ 1.55, -0.8 ,  0.25]])

**Nilai Eigen dan Vector Eigen**

In [49]:
eig, vec_eig = np.linalg.eig(A)
print('Nilai eigen matriks A:')
print(eig)
print('Vektor eigen matriks A:')
print(vec_eig)

Nilai eigen matriks A:
[19.39079317 -1.9262474   0.53545423]
Vektor eigen matriks A:
[[-0.27295093 -0.54761756  0.15754422]
 [-0.6940728  -0.31621014 -0.8168342 ]
 [-0.66615369  0.7746781   0.55494297]]


**Matriks Identitas**

In [50]:
Identitas=np.identity(5)
print(Identitas)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [51]:
Identitas[:,3]

array([0., 0., 0., 1., 0.])

**Matriks Satuan**

In [52]:
Satuan=np.ones((2,3))
Satuan

array([[1., 1., 1.],
       [1., 1., 1.]])

**Matriks Nol**

In [53]:
MatriksNol=np.zeros(10)
MatriksNol

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Matriks Segitiga Atas dan Bawah**

In [54]:
M=np.array([[1,2,3],[4,5,6],[7,8,9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
Lower=np.tril(M, -1)
Lower

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [56]:
Upper=np.triu(M, 1)
Upper

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

**Matriks Dekomposisi LU**

In [57]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

P, L, U = la.lu(A)
print(P)

print(L)

print(U)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.7        1.         0.        ]
 [0.2        0.51612903 1.        ]]
[[10.          7.          8.        ]
 [ 0.          3.1         3.4       ]
 [ 0.          0.          0.64516129]]


# **Membangun Matriks Menggunakan Perulangan**

In [58]:
C = np.arange(0,10,1)
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
C**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [60]:
L = []
for i in C:
  L.append(i+1)
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [61]:
A=np.zeros([3,4])
baris, kolom = np.shape(A)
print(baris)
print(kolom)
print(A)
arr=[]
for i in range(baris):
    arr.append([])
    print(arr)
    print('*'*20)
    for j in range(kolom):
        arr[i].append((i+j)*2)
        print(arr)
print(np.array(arr))

3
4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[]]
********************
[[0]]
[[0, 2]]
[[0, 2, 4]]
[[0, 2, 4, 6]]
[[0, 2, 4, 6], []]
********************
[[0, 2, 4, 6], [2]]
[[0, 2, 4, 6], [2, 4]]
[[0, 2, 4, 6], [2, 4, 6]]
[[0, 2, 4, 6], [2, 4, 6, 8]]
[[0, 2, 4, 6], [2, 4, 6, 8], []]
********************
[[0, 2, 4, 6], [2, 4, 6, 8], [4]]
[[0, 2, 4, 6], [2, 4, 6, 8], [4, 6]]
[[0, 2, 4, 6], [2, 4, 6, 8], [4, 6, 8]]
[[0, 2, 4, 6], [2, 4, 6, 8], [4, 6, 8, 10]]
[[ 0  2  4  6]
 [ 2  4  6  8]
 [ 4  6  8 10]]


# Latihan



1. Buatlah array matriks identitas dengan ukuran 20x20!



In [62]:
A=np.identity(20)
A

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.


2. Buatlah array matriks dengan ukuran sesuai dengan array c dan dengan elemennya adalah bilangan 112!

      c=[20, 60, 50, 70, 90, 78, 46, 56]

In [63]:
c=np.array([20, 60, 50, 70, 90, 78, 46, 56])
c

array([20, 60, 50, 70, 90, 78, 46, 56])

In [65]:
c[c > 15] = 112
c

array([112, 112, 112, 112, 112, 112, 112, 112])